# Generated by Django 2.2.5 on 2021-04-09 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('markers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marker',
            name='name',
        ),
    ]
